### PR TITLE
Added support for grouping

### PR DESCRIPTION
**Pull request by Plazmaz**
This is basically a copy-pasta from segment's main repo with minor modifications to work with this version.

### CODE REVIEW

**Comment by ghickman** [comment]
@Plazmaz – this looks good to me but can you squash those two commits please.  Having a change followed by a fix before we start review makes reviewing harder.

**Comment by Plazmaz** [comment]
@ghickman yep! Sorry, should be better now.

**Review by ghickman — APPROVED** [review]
👌

**Comment by ghickman** [comment]
I've released this as 1.1.0 on [PyPI](https://pypi.python.org/pypi/segment-queue).

**Pull request merged**
